{{- if and (not .Values.cloudflare.existingSecret) (or .Values.cloudflare.apiToken .Values.cloudflare.zoneID) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared-dns-controller.fullname" . }}-cloudflare
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-dns-controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.cloudflare.apiTokenKey }}: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  {{ .Values.cloudflare.zoneIDKey }}: {{ .Values.cloudflare.zoneID | b64enc | quote }}
{{- end }}
